database:
  dataSource: localhost
  port: 3306
  
  user: root
  password: localhost

  poolSize: 32

  schema: pilipala_fs

  table: 
    record: record
    stack: stack
    comment: comment
    token: token
